id = "lc3asm"
name = "LC3 Assembly"
description = "Simple LC3 TS grammar extension for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Adrian Brady"]
repository = "https://github.com/DauntingPear/zed-lc3asm"

[grammars.lc3asm]
repository = "https://github.com/DauntingPear/tree-sitter-lc3asm"
commit = "d264ebf319b88f6078334b7c8324b728a199f4f7"
